# Aiven Kafka connection configuration for Production
spring.kafka.bootstrap-servers=axedrobe-abhimanyuvishwakarma9228-0b92.h.aivencloud.com:13451
spring.kafka.properties.security.protocol=SSL
spring.ssl.bundle.pem.aiven.keystore.certificate=file:${KAFKA_CERT_PATH:./certs/service.cert}
spring.ssl.bundle.pem.aiven.keystore.private-key=file:${KAFKA_KEY_PATH:./certs/service.key}
spring.ssl.bundle.pem.aiven.truststore.certificate=file:${KAFKA_CA_CERT_PATH:./certs/ca.pem}
spring.kafka.ssl.bundle=aiven

# Aiven MySQL connection configuration for Production
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&sslMode=REQUIRED&trustCertificateKeyStoreUrl=file:${KAFKA_CA_CERT_PATH:/etc/secrets/ca.pem}&trustCertificateKeyStoreType=PEM
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
